version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: latinad-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - latinad-net

  nginx:
    image: nginx:latest
    container_name: latinad-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - latinad-net

  db:
    image: mysql:8.0
    container_name: latinad-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: latinad
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: latinad
      MYSQL_PASSWORD: latinad123
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - latinad-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - latinad-net

networks:
  latinad-net:

volumes:
  dbdata:
